package io.github.rafalpawlisz.shelfie.ui.theme

import androidx.compose.ui.graphics.Color

// Brand palette generated (Material Theme Builder style) from the launcher
// icon's sage green seed #33705A. Tones follow the M3 mapping: 40/90/10 for
// light roles, 80/30/20/90 for dark ones.

// Light scheme
val PrimaryLight = Color(0xFF2C6A4F)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFAFF2D0)
val OnPrimaryContainerLight = Color(0xFF002114)
val SecondaryLight = Color(0xFF4D6357)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCFE9D9)
val OnSecondaryContainerLight = Color(0xFF0A1F15)
val TertiaryLight = Color(0xFF3D6473)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC1E9FB)
val OnTertiaryContainerLight = Color(0xFF001F2A)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF5FBF4)
val OnBackgroundLight = Color(0xFF171D19)
val SurfaceLight = Color(0xFFF5FBF4)
val OnSurfaceLight = Color(0xFF171D19)
val SurfaceVariantLight = Color(0xFFDBE5DD)
val OnSurfaceVariantLight = Color(0xFF404943)
val OutlineLight = Color(0xFF707973)
val OutlineVariantLight = Color(0xFFBFC9C1)
val InverseSurfaceLight = Color(0xFF2C322D)
val InverseOnSurfaceLight = Color(0xFFEDF2EC)
val InversePrimaryLight = Color(0xFF93D5B4)
val SurfaceDimLight = Color(0xFFD6DCD6)
val SurfaceBrightLight = Color(0xFFF5FBF4)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFEFF5EF)
val SurfaceContainerLight = Color(0xFFE9EFE9)
val SurfaceContainerHighLight = Color(0xFFE3EAE4)
val SurfaceContainerHighestLight = Color(0xFFDEE4DE)

// Dark scheme
val PrimaryDark = Color(0xFF93D5B4)
val OnPrimaryDark = Color(0xFF003824)
val PrimaryContainerDark = Color(0xFF0D5138)
val OnPrimaryContainerDark = Color(0xFFAFF2D0)
val SecondaryDark = Color(0xFFB3CCBB)
val OnSecondaryDark = Color(0xFF1F352A)
val SecondaryContainerDark = Color(0xFF354B3F)
val OnSecondaryContainerDark = Color(0xFFCFE9D9)
val TertiaryDark = Color(0xFFA5CDDF)
val OnTertiaryDark = Color(0xFF073543)
val TertiaryContainerDark = Color(0xFF244C5B)
val OnTertiaryContainerDark = Color(0xFFC1E9FB)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF0F1512)
val OnBackgroundDark = Color(0xFFDFE4DD)
val SurfaceDark = Color(0xFF0F1512)
val OnSurfaceDark = Color(0xFFDFE4DD)
val SurfaceVariantDark = Color(0xFF404943)
val OnSurfaceVariantDark = Color(0xFFBFC9C1)
val OutlineDark = Color(0xFF8A938C)
val OutlineVariantDark = Color(0xFF404943)
val InverseSurfaceDark = Color(0xFFDFE4DD)
val InverseOnSurfaceDark = Color(0xFF2C322D)
val InversePrimaryDark = Color(0xFF2C6A4F)
val SurfaceDimDark = Color(0xFF0F1512)
val SurfaceBrightDark = Color(0xFF353B37)
val SurfaceContainerLowestDark = Color(0xFF0A100C)
val SurfaceContainerLowDark = Color(0xFF171D19)
val SurfaceContainerDark = Color(0xFF1B211D)
val SurfaceContainerHighDark = Color(0xFF252B27)
val SurfaceContainerHighestDark = Color(0xFF303632)
